# Generated by Django 4.2.2 on 2023-08-13 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('products', models.ManyToManyField(related_name='products', to='main.cardproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Kategoriya slugi')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Toliq ism')),
                ('province', models.CharField(choices=[('Toshkent', 'Toshkent'), ('Andijon', 'Andijon'), ('Namangan', 'Namangan'), ("Farg'ona", "Farg'ona"), ('Samarqand', 'Samarqand'), ('Jizzax', 'Jizzax'), ('Buxoro', 'Buxoro'), ('Qashqadaryo', 'Qashqadaryo'), ('Surxondaryo', 'Surxondaryo'), ('Xorazm', 'Xorazm'), ('Navoiy', 'Navoiy'), ('Sirdaryo', 'Sirdaryo'), ('Qoraqalpogiston', 'Qoraqalpogiston')], max_length=255, verbose_name='Viloyat')),
                ('city', models.CharField(max_length=255, verbose_name='Shahar')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefon raqam')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Yetkazib berildi', 'Yetkazib berildi'), ('Korib chiqilyapti', 'Korib chiqilyapti'), ('Korilmadi', 'Korilmadi')], default='Korilmadi', max_length=255, verbose_name='Holat')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.cart', verbose_name='Savatcha')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Taom nomi')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='narxi')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Necha foiz chegirma ?')),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='main.category')),
            ],
        ),
        migrations.AddField(
            model_name='cardproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='main.food'),
        ),
    ]
