# Generated by Django 4.2.2 on 2023-08-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_food_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food',
            new_name='Product',
        ),
    ]
