# Generated by Django 4.2.2 on 2023-08-15 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='province',
        ),
    ]
